services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    volumes:
      - ./clickhouse/user.xml:/etc/clickhouse-server/users.d/my-user.xml
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.d/my-config.xml
    ports:
      - 8123:8123
      - 9000:9000
      - 9009:9009
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/?query=SELECT%201
      interval: 5s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    depends_on:
      clickhouse:
        condition: service_healthy
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    restart: unless-stopped
  nextjs-app:
    depends_on:
      clickhouse:
        condition: service_healthy
    build: .
    ports:
      - 3004:3000
    environment:
      - CLICKHOUSE_URI=http://clickhouse:8123
    restart: unless-stopped
  worker:
    depends_on:
      clickhouse:
        condition: service_healthy
    build:
      dockerfile: ./worker.Dockerfile
    environment:
      - CLICKHOUSE_URI=http://clickhouse:8123
    restart: unless-stopped
