services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.3
    volumes:
      - ./clickhouse/user.xml:/etc/clickhouse-server/users.d/my-user.xml
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.d/my-config.xml
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/?query=SELECT%201
      interval: 5s
      timeout: 10s
      retries: 3
    restart: on-failure

  redis:
    image: redis:7.2.4
    restart: on-failure

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    depends_on:
      clickhouse:
        condition: service_healthy
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    restart: on-failure

  nextjs-app:
    depends_on:
      clickhouse:
        condition: service_healthy
      app-db:
        condition: service_started
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3004:3000
    environment:
      - CLICKHOUSE_URI=http://clickhouse:8123
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://user:password@app-db:5432/microblame
      - PASSWORD_ENCRYPTION_SECRET_FILE=/run/secrets/password_encryption_secret
    volumes:
      - ./secrets:/run/secrets
    restart: on-failure

  app-db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: microblame
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: on-failure

  worker:
    depends_on:
      clickhouse:
        condition: service_healthy
    build:
      dockerfile: ./worker.Dockerfile
    environment:
      - CLICKHOUSE_URI=http://clickhouse:8123
      - REDIS_URL=redis://redis:6379
    command: bun run scripts/tracedQueriesGeneratorStart.ts
    restart: on-failure

  # connection-worker:
  #   depends_on:
  #     clickhouse:
  #       condition: service_healthy
  #   build:
  #     dockerfile: ./worker.Dockerfile
  #   environment:
  #     - CLICKHOUSE_URI=http://clickhouse:8123
  #     - REDIS_URL=redis://redis:6379
  #     - DATABASE_URL=postgres://user:password@app-db:5432/microblame
  #     - PASSWORD_ENCRYPTION_SECRET_FILE=/run/secrets/password_encryption_secret
  #   volumes:
  #     - ./secrets:/run/secrets
  #   command: bun run src/utils/connection-worker/connectionWorker.ts
  #   restart: on-failure
